### PR TITLE
Merge jdk:jdk-24+19

### PR DESCRIPTION
**Pull request by AntonKozlov**
Merge jdk:jdk-24+19

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/crac.git pull/159/head:pull/159` \
`$ git checkout pull/159`

Update a local copy of the PR: \
`$ git checkout pull/159` \
`$ git pull https://git.openjdk.org/crac.git pull/159/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 159`

View PR using the GUI difftool: \
`$ git pr show -t 159`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/crac/pull/159.diff">https://git.openjdk.org/crac/pull/159.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/crac/pull/159#issuecomment-2479022512)
</details>

### CODE REVIEW

**Comment by rvansa** [comment]
I guess this supersedes https://github.com/openjdk/crac/pull/156

**Comment by AntonKozlov** [comment]
Yes. I'm trying the new way how we sync mainline with crac, so #156 slipped from my attention. My appologizes.

**Pull request merged**
