### PR TITLE
Print additional info for socket which still opened on checkpoint

### PR DESCRIPTION
**Pull request by wkia**
Added printing for socket port.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Radim Vansa](https://openjdk.org/census#rvansa) (@rvansa - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/crac.git pull/142/head:pull/142` \
`$ git checkout pull/142`

Update a local copy of the PR: \
`$ git checkout pull/142` \
`$ git pull https://git.openjdk.org/crac.git pull/142/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 142`

View PR using the GUI difftool: \
`$ git pr show -t 142`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/crac/pull/142.diff">https://git.openjdk.org/crac/pull/142.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/crac/pull/142#issuecomment-1820397961)

### CODE REVIEW

**Comment by rvansa** [comment]
LGTM, but GHA shows unusually high number of failures on linux x86 - could you check if these are related?

**Comment by wkia** [comment]
> LGTM, but GHA shows unusually high number of failures on linux x86 - could you check if these are related?

It doesn't related to the change as far as I see, the failure seems a kind of random fail:
- 2 tests failed with timeout in hs/tier1
- 1 test from langtools/tier1 failed on linux_x86
- recursiveCheckpoint failed on MacOs, as far as I know it is known issue?

**Review by rvansa — APPROVED** [review]

**Pull request closed without merging**
