### PR TITLE
Synchronize CPUFeatures with JDK trunk

### PR DESCRIPTION
**Pull request by jankratochvil**
---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Anton Kozlov](https://openjdk.org/census#akozlov) (@AntonKozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/crac.git pull/105/head:pull/105` \
`$ git checkout pull/105`

Update a local copy of the PR: \
`$ git checkout pull/105` \
`$ git pull https://git.openjdk.org/crac.git pull/105/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 105`

View PR using the GUI difftool: \
`$ git pr show -t 105`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/crac/pull/105.diff">https://git.openjdk.org/crac/pull/105.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/crac/pull/105#issuecomment-1676357246)

### CODE REVIEW

**Review by AntonKozlov — APPROVED** [review]
I assume that each CPU feature should be in GLIBC_DISABLE() or GLIBC_UNSUPPORTED() set. All new CPU features were added here. LGTM.

**Comment by jankratochvil** [comment]
> I assume that each CPU feature should be in GLIBC_DISABLE() or GLIBC_UNSUPPORTED() set.

Yes. And the `GLIBC_DISABLE()` set must be the same as `EXCESSIVE()` set. Which reminds me it could be simplified a bit but that will be a different patch.

**Pull request closed without merging**
