### PR TITLE
Changing CRaCResetStartTime flag defaults

### PR DESCRIPTION
**Pull request by wkia**
By the request in this comment https://github.com/openjdk/crac/pull/130/files#r1373722320

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Anton Kozlov](https://openjdk.org/census#akozlov) (@AntonKozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/crac.git pull/135/head:pull/135` \
`$ git checkout pull/135`

Update a local copy of the PR: \
`$ git checkout pull/135` \
`$ git pull https://git.openjdk.org/crac.git pull/135/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 135`

View PR using the GUI difftool: \
`$ git pr show -t 135`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/crac/pull/135.diff">https://git.openjdk.org/crac/pull/135.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/crac/pull/135#issuecomment-1782674754)

### CODE REVIEW

**Review by AntonKozlov — APPROVED** [review]
LGTM, thank you!

**Comment by rvansa** [comment]
@wkia Sorry to chime in rather late, but now it seems that this flag can be set only before checkpoint; why is that? Is there an issue in making this both diagnostic and restore-settable? (I guess that `UnlockDiagnosticOptions` might need to become restore-settable, too, but I don't see an issue with that)

**Comment by wkia** [comment]
@rvansa You're right, thanks. 
Need to be reviewed by @AntonKozlov also.  Should we change `UnlockDiagnosticOptions` to `RESTORE_SETTABLE` as well? If not,  `CRaCResetStartTime` will be available on checkpoint only as a diagnostic option.

**Review by AntonKozlov — APPROVED** [review]
LGTM, thank you!

**Pull request closed without merging**
