### PR TITLE
GLIBC->CPU flags optimization

### PR DESCRIPTION
**Pull request by jankratochvil**
Reduce the number of `GLIBC_*` flags when it can use existing `CPU_*` flags.
This patch was split out of PR #136.

```
 2 files changed, 9 insertions(+), 17 deletions(-)
```
So I find it clearly an improvement.
As an explanation: I created the GLIBC_* namespace in addition to the existing upstream CPU_* namespace. And some my additions in GLIBC_* namespace have now appeared by https://github.com/openjdk/jdk/commit/d50b6eb342e9ec96d1a01dafc317e00725dc84c0 also in the upstream CPU_* namespace. They were missing in the CPU_* namespace when I was implementing it. So we can remove the duplicity from GLIBC_* namespace.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Radim Vansa](https://openjdk.org/census#rvansa) (@rvansa - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/crac.git pull/139/head:pull/139` \
`$ git checkout pull/139`

Update a local copy of the PR: \
`$ git checkout pull/139` \
`$ git pull https://git.openjdk.org/crac.git pull/139/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 139`

View PR using the GUI difftool: \
`$ git pr show -t 139`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/crac/pull/139.diff">https://git.openjdk.org/crac/pull/139.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/crac/pull/139#issuecomment-1805486159)

### CODE REVIEW

**Comment by jankratochvil** [comment]
ping, it blocks #112

**Review by rvansa — APPROVED** [review]

**Pull request closed without merging**
