### PR TITLE
Keep _features the same after CRaC restore

### PR DESCRIPTION
**Pull request by jankratochvil**
Extending `_features` may change ABI or existing JIT-compiled code. Unfortunately we cannot use more advanced CPU features after restore, we need to stick to the same features of CPU used to make the checkpoint file.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Anton Kozlov](https://openjdk.org/census#akozlov) (@AntonKozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/crac.git pull/103/head:pull/103` \
`$ git checkout pull/103`

Update a local copy of the PR: \
`$ git checkout pull/103` \
`$ git pull https://git.openjdk.org/crac.git pull/103/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 103`

View PR using the GUI difftool: \
`$ git pr show -t 103`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/crac/pull/103.diff">https://git.openjdk.org/crac/pull/103.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/crac/pull/103#issuecomment-1674674243)

### CODE REVIEW

**Comment by jankratochvil** [comment]
Is this update OK or not? Most of the changes (moving the methods under `VM_Version::CpuidInfo`) could be attempted to be upstreamed to OpenJDK as I find them as a cleanup.

**Review by AntonKozlov — APPROVED** [review]
LGTM, and thank you for the SUPPORTS() cleanup

**Pull request closed without merging**
