### PR TITLE
Fixing VMOptionsTest.java

### PR DESCRIPTION
**Pull request by wkia**
test/jdk/jdk/crac/VMOptionsTest.java fails in debug build because it expects that NativeMemoryTracking equals to"off", that is not true in debug build.

```
Exception in thread "main" java.lang.RuntimeException: assertEquals: expected off to equal summary
    at jdk.test.lib.Asserts.fail(Asserts.java:594)
    at jdk.test.lib.Asserts.assertEquals(Asserts.java:205)
    at jdk.test.lib.Asserts.assertEquals(Asserts.java:189)
    at VMOptionsTest.exec(VMOptionsTest.java:60)
    at jdk.test.lib.crac.CracTest.run(CracTest.java:155)
    at jdk.test.lib.crac.CracTest.main(CracTest.java:87)
```

This change fixes the issue by retrieving NMT value before checkpoint, and comparing later.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Radim Vansa](https://openjdk.org/census#rvansa) (@rvansa - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/crac.git pull/81/head:pull/81` \
`$ git checkout pull/81`

Update a local copy of the PR: \
`$ git checkout pull/81` \
`$ git pull https://git.openjdk.org/crac.git pull/81/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 81`

View PR using the GUI difftool: \
`$ git pr show -t 81`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/crac/pull/81.diff">https://git.openjdk.org/crac/pull/81.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/crac/pull/81#issuecomment-1589308428)

### CODE REVIEW

**Comment by wkia** [comment]
@rvansa Could you review please?

**Comment by rvansa** [comment]
Hi @wkia , the PR looks correct, but I wonder if we need to complicate things if the NMT default is not the same in different builds. I've picked this simply as a random specimen of the non-manageable opts (with string args); could you just use something else, e.g. `OnOutOfMemoryError`, or if you want to go with non-empty default there's `MetaspaceReclaimPolicy`?

**Comment by wkia** [comment]
Hi @rvansa,
If my understanding correct regarding NMT, the test checks that non-manageable options cannot be set on restore. If so, there is no need to focus on _default_ values. Ok, I will make appropriate changes.

**Review by rvansa — APPROVED** [review]
LGTM. Out of curiosity, did you find any issues with using the same bean after restore?

**Comment by wkia** [comment]
@rvansa 
> did you find any issues with using the same bean after restore?

No, there is no problem with it, I just tried to make the checks isolated to prevent any interference.

**Pull request closed without merging**
