### PR TITLE
Simplify CPUFeatures code

### PR DESCRIPTION
**Pull request by jankratochvil**
There is no functionality change. I guess the new code should be more simple and shorter. It was originally suggested by @AntonKozlov to use more functions than macros.

```
 1 file changed, 44 insertions(+), 82 deletions(-)
 ```
So I find it clearly an improvement.
The readable sub-commit is: https://github.com/openjdk/crac/pull/112/commits/6d9cb72b7a838dd4c9f107c5b71c4275005a0c23
Otherwise it gets messed up by the other commit just renaming things.
As an explanation: Original code had two lists of the same CPU features. An `EXCESSIVE` list and an `GLIBC_DISABLE` list. The had to be kept in sync (their sets being equal) which was sanity checked:
```
    if (PASTE_TOKENS(disable_handled_, kind) != PASTE_TOKENS(excessive_handled_, kind))                                                  \
```
So now there is the list just once (`EXCESSIVE`, the `GLIBC_DISABLE` one has been deleted). It looks stupid but when coding it I did not see it.
Coding both variants of #136 was needlessly more difficult without this pull request applied and now I have to rebase this pull request.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/crac.git pull/112/head:pull/112` \
`$ git checkout pull/112`

Update a local copy of the PR: \
`$ git checkout pull/112` \
`$ git pull https://git.openjdk.org/crac.git pull/112/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 112`

View PR using the GUI difftool: \
`$ git pr show -t 112`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/crac/pull/112.diff">https://git.openjdk.org/crac/pull/112.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/crac/pull/112#issuecomment-1722257521)

### CODE REVIEW

**Comment by rvansa** [comment]
As much as I'd like to keep the PR queue short I am unfamiliar with this part of codebase, I'll leave the review up to @AntonKozlov since he did the review last time.

**Comment by jankratochvil** [comment]
Please note the changes are split into two different commits to make the review easier.

**Comment by jankratochvil** [comment]
I have submitted it downstream, it can bubble up here upstream later.

**Pull request closed without merging**
